#!/usr/bin/python3
import sys
import math


def factory(num):
    if num % 2 == 0:
        print("{}={}*{}".format(num, int(num // 2), 2))
    else:
        sq = int(math.sqrt(num))
        for i in range(3, sq + 1, 2):
            if num % i == 0:
                print("{}={}*{}".format(num, int(num//i), i))
                return
            elif num % (sq + i + 1) == 0:
                print("{}={}*{}".format(num, sq+1+i, int(num//(sq+1+i))))
                return
            elif num % (sq - i + 1) == 0:
                print("{}={}*{}".format(num, sq-1, int(num//(sq+1-i))))
                return


def factors(filename):
    with open(filename, encoding="utf-8") as my_file:
        for i in my_file.readlines():
            n = int(i)
            result = factory(n)


if __name__ == "__main__":
    factors(sys.argv[1])
